"""initial migration

Revision ID: 10490ea94338
Revises: None
Create Date: 2016-04-07 14:34:28.649334

"""

# revision identifiers, used by Alembic.
revision = '10490ea94338'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
